version: '3.9'

services:
  #mongo db service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

#node js api
  api:
    container_name: node_api_container
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      Name: Kashinath_Borker
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}





